<div class="container top-120">

    <div class="row">
        <div class="col-md-4">

            <ul>
                <li class="bold"><?=$this->translate("Office");?></li>
                <li>Rua Marquês das Minas Nº29 R/C Dir.</li>
                <li>2750 - 433 CASCAIS</li>
                <li>Portugal</li>
                <li class="bold">info@arch05.com</li>
                <li><a href="http://www.facebook.com/pages/AR-CH-05/170273413071107"><img src="/projects/imagens/home/facebook_logo_pb.jpg" width="5%"></a></li>
            </ul>
            <ul>
                <li class="bold pad-top-15">Ana Sutherland</li>
                <li>&#97;&#110;&#97;&#115;&#117;&#116;&#104;&#101;&#114;&#108;&#97;&#110;&#100;&#64;&#97;&#114;&#99;&#104;&#48;&#53;&#46;&#99;&#111;&#109;</li>
                <li class="bold pad-top-10">Daniela Castelbranco</li>
                <li>danielacastelbranco@arch05.com</li>
                <li class="bold pad-top-10">Hugo Afonso</li>
                <li><?=$this->translate("mob:");?> +351 916 061 568</li>
                <li>hugoafonso@arch05.com</li>
                <li class="bold pad-top-10">Marta Ribeiro Coelho</li>
                <li><?=$this->translate("mob:");?> +351 936 686 226</li>
                <li>martacoelho@arch05.com</li>
                <li class="bold pad-top-10">Joana Netto </li>
                <li>joanarogan@arch05.com</li>
                <li class="bold pad-top-10">Miguel Cordeiro</li>
                <li><?=$this->translate("mob:");?> +351 962 921 525</li>
                <li>miguelcordeiro@arch05.com</li>
            </ul>

        </div>
        <div class="col-md-4">
            <img src="/projects/projects/imagens/67pl.png" alt="">
        </div>

    </div>
    <?=$this->back();?>
</div>

