<?php $html = new RPS_Aux_Home(); ?>
<?php $html->setControllerName("project"); ?>

<div class="container top-120">
    <div class="row">
        <div class="col-md-12">
            <div class="grid">
                <?php
                    $html->setImageSrc("/projects/imagens/home/wc_02.jpg");
                    $html->setID(RPS_Aux_Home::REMODELACAO);
                    $html->setURL("is_aim");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/pero_boi.jpg");
                    $html->setID(RPS_Aux_Home::CONSTRUCAO);
                    $html->setURL("peroboi");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/luanda.jpg");
                    $html->setID(RPS_Aux_Home::CONSTRUCAO);
                    $html->setURL("luandahouse");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/3_.jpg");
                    $html->setID(RPS_Aux_Home::REMODELACAO);
                    $html->setURL("cruzdapedra");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/fire_boat.jpg");
                    $html->setID(RPS_Aux_Home::CONSTRUCAO);
                    $html->setURL("boatshelter");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/flag.jpg");
                    $html->setID(RPS_Aux_Home::REMODELACAO);
                    $html->setURL("flag");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/forum.jpg");
                    $html->setID(RPS_Aux_Home::REMODELACAO);
                    $html->setURL("forum");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/marina.jpg");
                    $html->setID(RPS_Aux_Home::CONSTRUCAO);
                    $html->setURL("restaurant");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/mesa_rogan.jpg");
                    $html->setID(RPS_Aux_Home::DESIGN);
                    $html->setURL("rogantable");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/mascara.jpg");
                    $html->setID(RPS_Aux_Home::CONSTRUCAO);
                    $html->setURL("lubango");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/alcantara.jpg");
                    $html->setID(RPS_Aux_Home::REMODELACAO);
                    $html->setURL("alcantara");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/bd.jpg");
                    $html->setID(RPS_Aux_Home::DESIGN);
                    $html->setURL("amadorabd");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/span_01_logo.jpg");
                    $html->setID(RPS_Aux_Home::REMODELACAO);
                    $html->setURL("spanhouse");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/ilustration.jpg");
                    $html->setID(RPS_Aux_Home::DESIGN);
                    $html->setURL("illustration");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/tentugal.jpg");
                    $html->setID(RPS_Aux_Home::CONSTRUCAO);
                    $html->setURL("tentugal");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/office_building.jpg");
                    $html->setID(RPS_Aux_Home::CONSTRUCAO);
                    $html->setURL("building");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/colar_amarelo.jpg");
                    $html->setID(RPS_Aux_Home::DESIGN);
                    $html->setURL("stagewear");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/informality.jpg");
                    $html->setID(RPS_Aux_Home::CONSTRUCAO);
                    $html->setURL("informality");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/crochet.jpg");
                    $html->setID(RPS_Aux_Home::DESIGN);
                    $html->setURL("neckgather");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/s4m.jpg");
                    $html->setID(RPS_Aux_Home::CONSTRUCAO);
                    $html->setURL("s4m");
                    echo $html->render();

                    $html->setImageSrc("/projects/imagens/home/rest.jpg");
                $html->setID(RPS_Aux_Home::REMODELACAO);
                $html->setURL("restcascais");
                echo $html->render();

                $html->setImageSrc("/projects/imagens/home/_2.jpg");
                $html->setID(RPS_Aux_Home::REMODELACAO);
                $html->setURL("torel");
                echo $html->render();
                ?>
            </div>
        </div>
    </div>
</div>