<div class="container top-120">
    <div class="row">
        <div class="col-md-3 justify">

            <p class="bold"><?=$this->translate('By Service');?></p>

            <ul class="ul-square">
                <li><?=$this->translate('Architecture');?></li>
                <li><?=$this->translate('Engineering');?></li>
                <li><?=$this->translate('Urban Planning');?></li>
                <li><?=$this->translate('Landscape');?></li>
                <li><?=$this->translate('Topography');?></li>
                <li><?=$this->translate('Industrial Design');?></li>
                <li><?=$this->translate('3D modelling');?></li>
                <li><?=$this->translate('Project coordination (construction works on Class V and above)');?></li>
                <li><?=$this->translate('Technical supervision of construction sites (Class III, IV, V, heritage buildings, etc.)');?></li>
                <li><?=$this->translate('Construction work oversight (Class III, IV, V, heritage buildings, etc.)');?></li>
                <li><?=$this->translate('Consulting on Architectural Heritage and Urban Renewal');?></li>
                <li><?=$this->translate('Building inspections and reports');?></li>

            </ul>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-3 justify">
            <p class="bold"><?=$this->translate('Construction');?></p>

            <ul class="ul-square top-30">
                <li><?=$this->translate('Rehabilitation of buildings');?></li>
                <li><?=$this->translate('Rehabilitation of architectural heritage');?></li>
                <li><?=$this->translate('Maintenance Work and Prevention');?></li>
                <li><?=$this->translate('Inspections');?></li>
            </ul>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-3 justify">
            <p class="bold"><?=$this->translate('Conservation and Restoration');?></p>

            <ul class="ul-square top-30">
                <li><?=$this->translate('Interventions in work areas in tiles, sculpture, stucco, painting, mural painting, stone materials, furniture, metal, gold carving, textiles, ceramics');?></li>
             </ul>
        </div>

    </div>
    <?=$this->back();?>
</div>