<div class="container top-120">
    <div class="row">
        <div class="col-md-3 justify">
            <p class="bold"><?=$this->translate('What we do');?></p>
            <p><?=$this->translate('We are a full service architecture, planning, interior design team.');?></p>
            <p><?=$this->translate('We can help you define building and construction projects including:');?></p>
            <ul class="ul-square">
                <li><?=$this->translate('Analysis of your space allocation needs');?></li>
                <li><?=$this->translate('Building surveys and site evaluation');?></li>
                <li><?=$this->translate('Establishing a preliminary construction budget and schedule');?></li>
                <li><?=$this->translate('Preliminary studies');?></li>
                <li><?=$this->translate('Proposals, plans, elevations, perspective drawings and renderings');?></li>
                <li><?=$this->translate('Documents for building and construction permit applications');?></li>
                <li><?=$this->translate('Design and build competitions');?></li>
                <li><?=$this->translate('Construction details');?></li>
                <li><?=$this->translate('Consulting, project management and coordination');?></li>
                <li><?=$this->translate('Market feasibility studies');?></li>
                <li><?=$this->translate('Sustainable Design');?></li>
                <li><?=$this->translate('Technical Assistance');?></li>
                <li><?=$this->translate('Verification of applicable laws and building codes');?></li>
                <li><?=$this->translate('Preparation of tender documents for works contracts');?></li>
            </ul>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-3 justify">
            <p class="bold"><?=$this->translate('Sustainable construction');?></p>
            <p><?=$this->translate('It is our goal to build a self-sustaining habitats, a living organism that is interconnected with its environment, sharing resources.');?></p>
            <p><?=$this->translate('We investigate all technologies and construction methods in the search of cost-effective and enduring solutions.');?></p>
            <p><?=$this->translate('We focus on developing buildings and spaces that respond to context and environment.');?></p>


            <ul class="ul-square top-30">
                <li><?=$this->translate('Passive solar architecture - design / project');?></li>
                <li><?=$this->translate('Choice of air conditioning solutions / insulation / energy optimization');?></li>
                <li><?=$this->translate('Use of eco-friendly materials');?></li>
                <li><?=$this->translate('Choice of local materials - reduced carbon footprint');?></li>
            </ul>

            <p class="top-40">
                <?=$this->translate('To work in Portugal, please read:');?>
                <a href="/projects/pdf/trabalhar_com_um_arquitecto.pdf"><i class="fa fa-file-pdf-o"></i> Link PDF</a>
            </p>

        </div>
        <div class="col-md-1"></div>
        <div class="col-md-3">
            <img src="/projects/whatwedo/imagens/roda.jpg" />
        </div>

    </div>
    <?=$this->back();?>
</div>

