<div class="container top-120">

	<div class="row">
		<div class="col-md-3 justify">
			<p class="bold"><?=$this->translate('Our targets and strategys');?></p>
			<p><?=$this->translate('We are a team of architects based in Lisbon, London, and Amsterdam with strong relations in Macau – this makes it easy and practical to arrange meetings, discussions and presentations in all locations.');?></p>
			<p><?=$this->translate('We have studied and practice architecture in various ways, from the smallest object, office buildings, housing and major urban strategy.');?></p>
			<p><?=$this->translate('We are connected by a shared vision of community and an ethical way of working where language and shape are secondary to thought and meaning.');?></p>
			<p>
				<?=$this->translate('Are you based in Amsterdam and want to develop a project in London?');?><br />
				<?=$this->translate('Are you living in England and need to renovate a house in Portugal?');?><br />
				<?=$this->translate('Are you in Lisbon and need associations in Macau?');?><br />
			</p>
			<p><?=$this->translate('We can be your executive architect dealing with planning application processes or overseeing a building site locally while you meet a member of our team wherever you need.');?></p>

		</div>

        <div class="col-md-4">
            <div class="top_image"><img src="/projects/whoweare/imagens/pentagrama.png" /></div>

        </div>
        <div class="col-md-4">
            <ul>
            	<li><img src="/projects/whoweare/imagens/miguel.jpg" /></li>
                <li class="pad-top-5"><img src="/projects/whoweare/imagens/ana.jpg" /></li>
                <li class="pad-top-5"><img src="/projects/whoweare/imagens/daniela.jpg" /></li>
                <li class="pad-top-5"><img src="/projects/whoweare/imagens/hugo.jpg" /></li>
                <li class="pad-top-5"><img src="/projects/whoweare/imagens/marta.png" /></li>
				<li class="pad-top-5"><img src="/projects/whoweare/imagens/helena.png" /></li>
                
            </ul>



	</div>

</div>
    <?=$this->back();?>
</div>