<div class="container top-120">

    <div class="row">
        <div class="col-md-4">

            <p class="bold"><?=$this->translate('project');?></p>
            <p><?=$this->translate('project list');?></p>
            <p class="bold"><?=$this->translate('public');?></p>

            <ul class="ul-square">
                <li><?=$this->translate('nossa sra da anunciação church');?></li>
                <li><?=$this->translate('forum consultants ltd');?></li>
                <li><?=$this->translate('olival basto comunity centre');?></li>
                <li><?=$this->translate('industrial building in an entertainment building');?></li>
                <li><?=$this->translate('macau international airport 11 public toilets');?></li>
                <li><?=$this->translate('fire boat shelter');?></li>
                <li><?=$this->translate('social welfare department office interior design');?></li>
                <li><?=$this->translate('bivet veterinary clinic');?></li>
                <li><?=$this->translate('marina restaurants');?></li>
                <li><?=$this->translate('customs office façade design');?></li>
                <li><?=$this->translate('social welfare department office building');?></li>
                <li><?=$this->translate('cam office interior design and fit out');?></li>
                <li><?=$this->translate('flag – computer learning centre');?></li>
                <li><?=$this->translate('l.n.águas grundfos warehouse and offices');?></li>
                <li><?=$this->translate('aveiro building, (dental clinic, retail unit and restaurant)');?></li>
                <li><?=$this->translate('pedestrian bridge');?></li>
                <li><?=$this->translate('castro verde playground');?></li>
                <li><?=$this->translate('jacinto faleiro elderly centre');?></li>
                <li><?=$this->translate('antónio prates foundation');?></li>
                <li><?=$this->translate('silves, tavira quarteira e lagoa’s healthcentres');?></li>
            </ul>
            <p class="bold"><?=$this->translate('retail');?></p>
            <ul class="ul-square">
                <li><?=$this->translate('porto de abrigo restaurant');?></li>
                <li><?=$this->translate('adega restaurant');?></li>
                <li><?=$this->translate('tutti sensi shop');?></li>
                <li><?=$this->translate('gourmet café – oficina do gosto');?></li>
                <li><?=$this->translate('5 decoration shops for michele k');?></li>
                <li><?=$this->translate('jeweller’s shop');?></li>
                <li><?=$this->translate('tuxa hairdresser');?></li>
            </ul>
            <p class="bold"><?=$this->translate('residential');?></p>
            <ul class="ul-square">
                <li><?=$this->translate('dr. raposo house');?></li>
                <li><?=$this->translate('plátanos condominium');?></li>
                <li><?=$this->translate('pero boi house');?></li>
                <li><?=$this->translate('old house refurbishment');?></li>
                <li><?=$this->translate('3 houses');?></li>
                <li><?=$this->translate('carnaxide apartment');?></li>
                <li><?=$this->translate('quinta mont-fleuri studio');?></li>
                <li><?=$this->translate('alfaquiques house');?></li>
                <li><?=$this->translate('albogas small house');?></li>
                <li><?=$this->translate('portela kitchen layout');?></li>
                <li><?=$this->translate('martim freire house');?></li>
                <li><?=$this->translate('claudia belchior house');?></li>
                <li><?=$this->translate('sassoeiros house');?></li>
                <li><?=$this->translate('luis bivar avenue kitchen and w.c');?></li>
                <li><?=$this->translate('lapa kitchen and w.c. construction details');?></li>
                <li><?=$this->translate('house in vialonga');?></li>
                <li><?=$this->translate('empreiteiro house');?></li>
                <li><?=$this->translate('mr. arruda house - azores');?></li>
                <li><?=$this->translate('ruraltur');?></li>
                <li><?=$this->translate('pires guerra house');?></li>
                <li><?=$this->translate('three model houses');?></li>
            </ul>
            <p class="bold"><?=$this->translate('competitions');?></p>
            <ul class="ul-square">
                <li><?=$this->translate('vimeiro golf hotel refurbishment competition');?></li>
                <li><?=$this->translate('luanda house - patio and pavillion competition');?></li>
                <li><?=$this->translate('car park');?></li>
                <li><?=$this->translate('martial arts sports complex');?></li>
                <li><?=$this->translate('library in santa maria island');?></li>
                <li><?=$this->translate('young artists digital photograph competition');?></li>
                <li><?=$this->translate('mondaine competition');?></li>
                <li><?=$this->translate('ifda competition');?></li>
                <li><?=$this->translate('rio maior bus terminal');?></li>
                <li><?=$this->translate('expresso/sojornal building');?></li>
            </ul>
            <p class="bold"><?=$this->translate('consultancy');?></p>
            <ul class="ul-square">
                <li><?=$this->translate('house construction viability - monchique');?></li>
                <li><?=$this->translate('house construction viability - manique');?></li>
                <li><?=$this->translate('commercial complex renovation from residential buildings');?></li>
                <li><?=$this->translate('housing fisability study - lote d');?></li>
                <li><?=$this->translate('gemini comercial centre refurbishment');?></li>
                <li><?=$this->translate('jfs fachade color scheme');?></li>
            </ul>
            <p class="bold"><?=$this->translate('masterplan');?></p>
            <ul class="ul-square">
                <li><?=$this->translate('lubango master plan, for cns - angola');?></li>
                <li><?=$this->translate('alto dos espalhatos, azores');?></li>
                <li><?=$this->translate('quinta da nascente, rio maior');?></li>
            </ul>
            <p class="bold"><?=$this->translate('masterplan');?></p>
            <ul class="ul-square">
                <li><?=$this->translate('“best 2003 portuguese comics” set, in the xiv internacional festival of comics in amadora (fibda)');?></li>
                <li><?=$this->translate('children’s scenic space in the xv internacional festival of comics in amadora');?></li>
                <li><?=$this->translate('two sets in the xviii internacional festival of comics in amadora');?></li>
            </ul>

        </div>
        <div class="col-lg-5">
            <img src="/projects/projects/imagens/cloud.jpg" alt="cloud" />
        </div>
    </div>

 <?=$this->back();?>
</div>

