<?=$this->doctype();?>
<html lang="<?=substr(Zend_Locale::findLocale(), 0, 2)?>">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?=$this->headTitle();?>
<?=$this->headMeta();?>
<?=$this->headLink();?>
<?=$this->headScript();?>
<?=$this->placeholder('js');?>
<?=$this->placeholder('scripts');?>
<?=$this->placeholder('css');?>
    <link href='https://fonts.googleapis.com/css?family=Raleway:300' rel='stylesheet' type='text/css'>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img src="/projects/imagens/comuns/arqt05.jpg"  width="72%"/> </a>
        </div>
    </div>
</nav>

<div id="rps_navcontainer" >

    <?php
        $loc = Zend_Locale::findLocale();
    ?>

<ul>
    
    <li><a href="/index/whatwedo"><?=$this->translate('Profile');?></a></li>
    <li><a href="/index/work"><?=$this->translate('Work');?></a></li>
    <li><a href="/index/whoweare"><?=$this->translate('The team');?></a></li>
    <li><a href="/index/contacts"><?=$this->translate('Contacts');?></a></li>


    <?php if ($loc == "en_US"): ?>
        <li style="padding-left: 100px;"><a href="/locale/index/locale/pt_PT/0/default/1/1">pt</a> <span style="color: red">|</span> <span style="color:black;padding-left: 15px">en</span></li>
    <?php else: ?>
        <li style="padding-left: 100px;"><span style="color:black;padding-right: 15px">pt</span> <span style="color: red">|</span> <a href="/locale/index/locale/en_US/0/default/1/1">en</a></li>
    <?php endif; ?>

</ul>
    </div>

<?php echo $this->FilterType(); ?>
<?php echo $this->layout()->content; ?>

</body>
</html>


